version: "3.7"
services:
  bot:
    build: .
    command: python bot.py
    depends_on:
      - cache
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ../data/guild_settings:/data
